Converted to Polymer 2.0 (#7)
notwaldorf/emoji-rain pull request #8
Opened 2017-07-11 09:15 UTC by mikeperret

Hi there

I made this work with Polymer 2.0:

- Changed emoji-rain.html to the new syntax
- emoji-rain.html: Added setTimeout to the resize method (works somehow more reliably)
- emoji-rain.html: "Speed" is now also an attribute/property
- Updated `iron-component-page` to 3.0.1 (added analysis.json)
- Not sure if necessary: I added polymer.json so it worked for me with `polymer serve` and `polymer test`

About this I am not sure: 
I also changed the paths of the HTML-Imports, as for me, the bower_components directory is in the same folder as index.html and emoji-rain.html. I hope I didn't mess anything up for you. But I think it should be fine when you can make a git clone, run `bower install `and then `polymer serve` and it works, correct? 

Also this is my first pull request ever, hope I didn't mess it up 😆

2017-07-31 23:38 UTC, notwaldorf requested changes
Thanks for the PR! There's a bunch of changes that aren't needed, though, since this is a standalone element (not a shipped demo)

2017-07-31 23:38 UTC, notwaldorf commented on polymer.json
> +  "entrypoint": "index.html",
Why is this file even needed?

2017-07-31 23:38 UTC, notwaldorf commented on polymer.json
> +  "entrypoint": "index.html",
Ah, please don't add a service worker. This is a standalone element, and a service worker is a user feature, not an element feature.

2017-07-31 23:38 UTC, notwaldorf commented on service-worker.js
> +console.log('Service worker disabled for development, will be generated at build time.');
Please remove, as mentioned.

2017-07-31 23:38 UTC, notwaldorf commented on test/basic.html
> +            //done(); (thrown error - why?)
Uncomment and add a `done` function to the test instead

2017-07-31 23:38 UTC, notwaldorf commented on test/index.html
> +  <script src="../bower_components/webcomponentsjs/webcomponents-lite.js"></script>
Not needed (see above)

2017-07-31 23:38 UTC, notwaldorf commented on test/basic.html
> +  <script src="../bower_components/webcomponentsjs/webcomponents-lite.js"></script>
Not needed (see above)

2017-07-31 23:38 UTC, notwaldorf commented on demo/index.html
> +  <script src="../bower_components/webcomponentsjs/webcomponents-lite.js"></script>
This isn't needed -- this element is meant to be a standalone element, so you should test it using `polymer serve`. See `github.com/polymerelements/paper-button` for another element sample.

2017-08-01 09:32 UTC, mikeperret commented
Thank you for your feedback and sorry for my lack of understanding - I should have gotten a lot more suspicious about changing all these paths in the first place.

**Changes**
- Removed polymer.json
- Removed service-worker.js
- Revoked changes of paths in `<imports>/<scripts>`-Tags in all .html files
- Removed a unnecessary console.log I added in emoji-rain.html
- Removed the speed-attribute I added in emoji-rain.html (because I think I should refactor it a bit and add it inside another PR)
- Fixed test/basic.html `done();` problem

2017-08-01 09:34 UTC, mikeperret commented on polymer.json
> +  "entrypoint": "index.html",
Not needed - honestly I thought it was needed to run "polymer serve" but it is not :-)

2018-02-28 19:13 UTC, notwaldorf approved these changes

2018-02-28 19:13 UTC, notwaldorf commented
Super late, but yay! Thanks for the PR!

2018-02-28 19:13 UTC, merged